<?php
use Illuminate\Support\Facades\Input;
?>
<!doctype html>
<html>

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
	<!-- Apple devices fullscreen -->
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<!-- Apple devices fullscreen -->
	<meta names="apple-mobile-web-app-status-bar-style" content="black-translucent" />
	<title></title>
	<style type="text/css" media="print">
        @page 
        {
            size: auto;   /* auto is the current printer page size */
            margin: 8mm;  /* this affects the margin in the printer settings */
        }

        body 
        {
            margin: 0px;  /* the margin on the content before printing */
       }
    </style>
	</head>
<body>
	<div style="width:200mm;  margin: auto;">
	  	<table width="100%">
			<tr>
				<td align='center' style="color:#8A0808;"><b>NEW MORNING STAR TRAVELS<br/><br/></td>
			</tr>
	  	</table>
	  	<table width="100%">
	  		<tr>
	  			<td style="float: left;">MORNING STRAR TRAVELS</td>
	  			<td style="float: right;">Date : {{date("d-m-Y h:i:sA")}}</td>
	  		</tr>
	  		<tr>
	  			<td style="float: left;">Booking Created By :  TEST EMPLOYEE</td>
	  			<td style="float: right;">Report Generated By :  TEST EMPLOYEE</td>
	  		</tr>
	  		<tr>
	  			<td colspan="1"><div style="text-align: center;font-size: 20px;font-weight: bold;">BUS BOOKING REPORT - MST150900243<br/></div></td>
	  		</tr>
	  		
	  	</table>
	  	<table width="100%" border='1' cellpadding='5' cellspacing='1' style="border: 1px solid green;border-collapse: collapse;">
	  		<tr><td colspan="2" style="text-align: center;background-color: #CBCECB; font-weight: bold;">CUSTOMER DETAILS</td></tr>
	  		<tr>
	  			<td>Customer Name </td><td>M KASI VISWANATH GARU</td>
	  		</tr>
	  		<tr>
	  			<td>Customer Phone Number </td><td>9848133861 / 9848067796</td>
	  		</tr>
	  		<tr>
	  			<td>Customer Email </td><td>M KASI VISWANATH GARU</td>
	  		</tr>
	  		<tr>
	  			<td>Customer Address </td><td>CHANDRAMOULI NAGAR 1ST LINE,GUNTUR</td>
	  		</tr>
	  	</table>
	  	<table style="margin: -2px; margin-top: 5px;">
	  		<tr>
	  			<td>
	  				<table width="100%" border='1' cellpadding='5' cellspacing='1' style="border: 1px solid green;border-collapse: collapse;">
				  		<tr><td colspan="2" style="text-align: center;background-color: #CBCECB; font-weight: bold;">CUSTOMER DETAILS</td></tr>
				  		<tr>
				  			<td>Customer Name </td><td>M KASI VISWANATH GARU</td>
				  		</tr>
				  		<tr>
				  			<td>Customer Phone Number </td><td>9848133861 / 9848067796</td>
				  		</tr>
				  		<tr>
				  			<td>Customer Email </td><td>M KASI VISWANATH GARU</td>
				  		</tr>
				  		<tr>
				  			<td>Customer Address </td><td>CHANDRAMOULI NAGAR 1ST LINE,GUNTUR</td>
				  		</tr>
				  	</table>
	  			</td>
	  			<td>
	  				<table width="100%" border='1' cellpadding='5' cellspacing='1' style="border: 1px solid green;border-collapse: collapse;">
				  		<tr><td colspan="2" style="text-align: center;background-color: #CBCECB; font-weight: bold;">CUSTOMER DETAILS</td></tr>
				  		<tr>
				  			<td>Customer Name </td><td>M KASI VISWANATH GARU</td>
				  		</tr>
				  		<tr>
				  			<td>Customer Phone Number </td><td>9848133861 / 9848067796</td>
				  		</tr>
				  		<tr>
				  			<td>Customer Email </td><td>M KASI VISWANATH GARU</td>
				  		</tr>
				  		<tr>
				  			<td>Customer Address </td><td>CHANDRAMOULI NAGAR 1ST LINE,GUNTUR</td>
				  		</tr>
				  	</table>
	  			</td>
	  		</tr>
	  	</table>
	  	<table width="100%" border='1' cellpadding='5' cellspacing='1' style="margin-top:5px; border: 1px solid green;border-collapse: collapse;">
	  		<tr><td colspan="2" style="text-align: center;background-color: #CBCECB; font-weight: bold;">BOOKING COST DETAILS</td></tr>
	  		<tr>
	  			<td>Customer Name </td><td>M KASI VISWANATH GARU</td>
	  		</tr>
	  		<tr>
	  			<td>Customer Phone Number </td><td>9848133861 / 9848067796</td>
	  		</tr>
	  		<tr>
	  			<td>Customer Email </td><td>M KASI VISWANATH GARU</td>
	  		</tr>
	  		<tr>
	  			<td>Customer Address </td><td>CHANDRAMOULI NAGAR 1ST LINE,GUNTUR</td>
	  		</tr>
	  	</table>
  	</div>
</body>
</html>
